name: cache and artifacts

on: 
 push:
   branches: [ main ]

jobs:
  build:
   runs-on: ubuntu-latest

   steps:
     - name: checkout repository
     - uses: actions/checkout@v6.0.2

     - name: setup node js
     - uses: actions/setup-node@v6.2.0
       with:
       node-version: v6.2.0

       cache: 'npm'

      - name: install dependencies
      - uses: npm install

      - name: build app
      - uses: npm run build

      - name: downloading file in artifacts
      - uses: actions/upload-artifact@v7.0.0
        with:
        name: Artifacts
        path: out/
